- name: Install cifs-utils
  package:
    name: cifs-utils
    state: present

- name: Fail if smb credentials file is not provided
  fail:
    msg: "You must pass -e smb_credentials=/path/to/creds"
  when: smb_credentials == ""

- name: Copy smb credentials
  copy:
    src: "{{ smb_credentials }}"
    dest: "{{ smb_creds_path }}"

- name: Fail if nfs-share string is not provided
  fail:
    msg: "You must pass -e nfs_share=//share/path"
  when: nfs_share == ""

- name: Make systemd unit for nfs mount
  template:
    src: nfs.mount.j2
    dest: /etc/systemd/system/nfs.mount
  notify:
    - Reload systemd
    - Restart nfs-mount

- name: Enable nfs-mount service
  systemd:
    name: nfs.mount
    enabled: yes
    state: started