#cloud-config

write_files:
 - path: /opt/application.yml
   content: !!binary |
    ${shinyproxy_config}

 - path: /opt/farm-config.yaml
   content: !!binary |
    ${farm_config}

 - path: /opt/key
   permissions: '0600'
   content: !!binary |
    ${private_key}

 - path: /etc/systemd/resolved.conf.d/dns.conf
   content: |
    [Resolve]
    DNS=172.18.255.1 172.18.255.2

 - path: /etc/systemd/system/sshtunnel.service
   content: |
    [Unit]
    Description=SSH Tunnel
    After=network.target

    [Service]
    Restart=always
    RestartSec=20
    User=root
    ExecStart=/bin/ssh -i /opt/key -o StrictHostKeyChecking=no -nNT -L 0.0.0.0:${proxy_port}:localhost:${proxy_port} ${proxy_user}@${proxy_host}

    [Install]
    WantedBy=multi-user.target

packages:
 - openjdk-21-jre-headless

runcmd:
 - [ wget, "https://www.shinyproxy.io/downloads/shinyproxy_3.1.1_amd64.deb" ]
 - apt install -y ./shinyproxy_3.1.1_amd64.deb
 - rm ./shinyproxy_3.1.1_amd64.deb
 - systemctl enable shinyproxy
 - mv /opt/application.yml /etc/shinyproxy/application.yml
 - systemctl restart shinyproxy
 - systemctl restart systemd-resolved
 - systemctl enable sshtunnel
 - systemctl start sshtunnel
