#cloud-config

# for some reason we have to set DNS address manually.
# should be changed if the DNS server gets a new IP
 - path: /etc/systemd/resolved.conf.d/dns.conf
   content: |
    [Resolve]
    DNS=172.18.255.1 172.18.255.2

runcmd:
 - systemctl restart systemd-resolved
