public_key     = "~/.ssh/id_rsa.pub"
farm_config    = "../config.yaml"
nfs_share      = "//nfs-server/share-name"
smbcredentials = "../smbcredentials"
infoblox_host  = "infoblox.com"
infoblox_user  = "username"
infoblox_pass  = "password"
