argument_specs:
  main:
    options:
      farmers_config:
        type: str
        required: true
        description: Path to farmers config file
      shinyproxy_version:
        type: str
        description: Version of the ShinyProxy to install
        default: "3.1.1"
